name: puzzle_repository
description: "Repository that handles puzzle"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  arkroot_puzzle_api:
    path: ../arkroot_puzzle_api
  equatable: ^2.0.5
  ntp: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
