include:
  - package:bloc_lint/recommended.yaml
  - package:very_good_analysis/analysis_options.7.0.0.yaml

analyzer:
  exclude: ["lib/**.g.dart"]

formatter:
  page_width: 80
  trailing_commas: preserve

linter:
  rules:
    public_member_api_docs: false
