include:
  - package:bloc_lint/recommended.yaml
  - package:very_good_analysis/analysis_options.9.0.0.yaml

analyzer:
  exclude: ["lib/**.g.dart"]

formatter:
  page_width: 80
  trailing_commas: preserve

linter:
  rules:
    # This is an app, not a package that will be consumed
    public_member_api_docs: false
    # Experimental and there are lots of false positives
    specify_nonobvious_property_types: false
