name: coverage

on: [check_run, check_suite]

permissions:
  id-token: write
  checks: write
  actions: read

jobs:
  upload_coverage:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.check_run.name }}
