name: coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, check_run]

permissions:
  contents: read
  id-token: write

jobs:
  upload_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Upload Coverage
        run: su - worker -c "echo $(whoami)"
