name: coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  check_run:
    types: [completed]

jobs:
  upload_coverage:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.requested_action.identifier }}
